apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  name: s2ioperator-v3.2.1
  namespace: ks-version
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/kubesphere-sigs/ks-versions
      branch: master
      name: ks-versions
      provider: github
    secret: {}
  phase: ready
  repositories:
  - action: release
    address: https://github.com/kubesphere/s2ioperator
    branch: master
    name: s2ioperator
    provider: github
    version: v3.2.1
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v3.2.1
