apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: "2022-04-21T03:45:15Z"
  labels:
    app.kubernetes.io/instance: ks-versions
  name: kubekey-v2.1.0-alpha.2
  namespace: ks-version
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/kubesphere-sigs/ks-versions
      branch: master
      name: ks-versions
      provider: github
    secret:
      name: linuxsuren-bot
      namespace: ks-releaser-system
  phase: draft
  repositories:
  - action: pre-release
    address: https://github.com/kubesphere/kubekey
    branch: release-2.1
    name: kubekey
    provider: github
    version: v2.1.0-alpha.2
  secret:
    name: release-bot
    namespace: release
  version: v2.1.0-alpha.2
status: {}
